### PR TITLE
/refuel cmd added, /spawncar modified to spawn car in dir of admin view

### PR DESCRIPTION
**Pull request by Moondarker**

### CODE REVIEW

**Comment by chinayern** [comment]
That's great. 
Thanks 
Big Love.

**Comment by robotstar78** [comment]
Frogive my complete noobishness, but am I to remove everything in red and add everything in green? Or just add it all in as is?

**Comment by arniegames4u** [comment]
Remove red add green


This message was sent from a mobile device

**Comment by robotstar78** [comment]
That's what I thought :/ it just keeps coming back with the following:

ZARE5, 22.11 2018 17:01:03
Can't compile mission init script'!
 
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//AdminTool//AdminTool.c(511): Multiple declaration of variable 'position'

**Comment by robotstar78** [comment]
It's this line that it's hanging on - 

vector position = Admin.GetPosition();

**Comment by arniegames4u** [comment]
Change position to position1 in the new command 


This message was sent from a mobile device

**Comment by arniegames4u** [comment]
The script works, they just orient north. 


This message was sent from a mobile device

**Comment by S4MT3K** [comment]
> 
> 
> You sir, are a bit of a genuis :)

In the message output of the refuel function add after the nearest_objects[i] 

.ToString()
Should look like this 
`Msgparam = new Param1( nearest_objects[i].ToString() +" refueled, " +fuelReq +"L added, all fluids maxed" );
										GetGame().RPCSingleParam(Admin, ERPCs.RPC_USER_ACTION_MESSAGE, Msgparam, true, AdminIdentity);`

dont forget the "<"string">" after param1, he erased it again -.-"
I just compiled it... Doesnt tested it, couse im struggling with latest update of DayZ. But maybe it helps...

**Comment by robotstar78** [comment]
You definitely are a genius :) Tested. All works like a charm! Well done you! Thanks!!!!!

**Comment by Moondarker** [comment]
Guys, in case of situation like this pls use issues and pull requests in forked repos :)

**Pull request closed without merging**
