### PR TITLE
Restructured readme

### PR DESCRIPTION
**Pull request by Slluxx**
Its by far not perfect and probably has some typos in it but its structured and you can actually read what to do

### CODE REVIEW

**Comment by Slluxx** [comment]
No worries m8. Anyone can criticize something and i know that most of them don't provide a better way of doing something.

**Comment by GravityWolfNotAmused** [comment]
@Slluxx 
https://github.com/Da0ne/DZMods#credits

> @Slluxx for teaching @GravityWolfNotAmused how not to suck at readme.md files.

**Comment by GravityWolfNotAmused** [comment]
Thank you for the help

**Comment by Slluxx** [comment]
@GravityWolfNotAmused no worries man

**Pull request closed without merging**
